'use client';

import { useState } from 'react';

export default function SuperAdminPage() {
  const [activeSection, setActiveSection] = useState('tenants');
  const [successMessage, setSuccessMessage] = useState('');
  const [tenants, setTenants] = useState([
    { id: 'org_001', name: 'Demo FMCG Company', plan: 'Growth', status: 'Active', users: 45, orders: '2.4K', gmv: '₹45L', created: '2026-01-15' },
    { id: 'org_002', name: 'Demo Pharma Limited', plan: 'Starter', status: 'Trial', users: 12, orders: '340', gmv: '₹8.5L', created: '2026-07-01' },
    { id: 'org_003', name: 'Agri Solutions Pvt Ltd', plan: 'Enterprise', status: 'Active', users: 120, orders: '8.5K', gmv: '₹2.1Cr', created: '2025-11-20' },
    { id: 'org_004', name: 'Paint World India', plan: 'Growth', status: 'Past Due', users: 35, orders: '1.8K', gmv: '₹32L', created: '2026-03-10' },
    { id: 'org_005', name: 'Consumer Goods Corp', plan: 'Starter', status: 'Suspended', users: 8, orders: '120', gmv: '₹3.2L', created: '2026-05-22' },
  ]);

  const plans = [
    { name: 'Starter', price: '₹9,999/mo', users: '10', distributors: '1', tenants: 15 },
    { name: 'Growth', price: '₹24,999/mo', users: '50', distributors: '5', tenants: 8 },
    { name: 'Enterprise', price: 'Custom', users: 'Unlimited', distributors: 'Unlimited', tenants: 3 },
  ];

  const systemHealth = { api: { status: 'healthy', uptime: '99.99%', responseTime: '142ms' }, mongodb: { status: 'healthy', connections: '45/100', storage: '2.4GB' }, redis: { status: 'healthy', memory: '128MB/256MB', hitRate: '94%' }, minio: { status: 'healthy', storage: '15GB/100GB', buckets: 8 } };

  const auditEvents = [
    { time: '10:30 AM', actor: 'admin@fmcg.com', action: 'USER_CREATED', entity: 'usr_123', tenant: 'org_001' },
    { time: '10:25 AM', actor: 'system', action: 'TENANT_SUSPENDED', entity: 'org_005', tenant: 'system' },
    { time: '10:20 AM', actor: 'support@bharatsales', action: 'IMPERSONATION_START', entity: 'org_004', tenant: 'system' },
    { time: '10:15 AM', actor: 'admin@pharma.com', action: 'PLAN_UPGRADED', entity: 'org_002', tenant: 'org_002' },
  ];

  const handleCreateTenant = () => { setSuccessMessage('New tenant created successfully!'); setTimeout(() => setSuccessMessage(''), 3000); };
  const handleImpersonate = (id: string) => { setSuccessMessage(`Impersonating tenant ${id}...`); setTimeout(() => setSuccessMessage(''), 2000); };

  return (
    <div className="min-h-screen bg-gray-50">
      {successMessage && (<div className="bg-green-50 border border-green-200 rounded-xl p-4 flex items-center justify-between max-w-7xl mx-auto mt-4 px-6"><div className="flex items-center space-x-2"><span className="text-green-600">✅</span><span className="text-sm text-green-800 font-medium">{successMessage}</span></div><button onClick={() => setSuccessMessage('')} className="text-green-600 hover:text-green-800">✕</button></div>)}
      <header className="bg-gray-900 text-white border-b border-gray-800"><div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between"><div className="flex items-center space-x-3"><div className="w-8 h-8 bg-gradient-to-br from-primary-500 to-saffron-500 rounded-lg flex items-center justify-center"><span className="text-white font-bold text-sm">SA</span></div><div><h1 className="text-lg font-bold">Super Admin Console</h1><p className="text-xs text-gray-400">Platform Operations & Management</p></div></div><span className="text-xs bg-green-900 text-green-300 px-2 py-1 rounded">System Healthy</span></div></header>
      <div className="max-w-7xl mx-auto px-6 py-6"><div className="flex space-x-1 bg-gray-100 rounded-lg p-1 mb-6 overflow-x-auto">{[{ id: 'tenants', label: 'Tenants', icon: '🏢' }, { id: 'plans', label: 'Plans & Billing', icon: '💳' }, { id: 'health', label: 'System Health', icon: '💚' }, { id: 'audit', label: 'Audit & Security', icon: '🔒' }].map((tab) => (<button key={tab.id} onClick={() => setActiveSection(tab.id)} className={`flex items-center space-x-2 px-4 py-2 rounded-md text-sm font-medium whitespace-nowrap ${activeSection === tab.id ? 'bg-white shadow-sm text-gray-900' : 'text-gray-500 hover:text-gray-700'}`}><span>{tab.icon}</span><span>{tab.label}</span></button>))}</div>
        {activeSection === 'tenants' && (<div className="space-y-6"><div className="grid grid-cols-4 gap-4"><div className="card text-center"><div className="text-2xl font-bold text-gray-900">{tenants.length}</div><div className="text-sm text-gray-500">Total Tenants</div></div><div className="card text-center"><div className="text-2xl font-bold text-green-600">{tenants.filter(t => t.status === 'Active').length}</div><div className="text-sm text-gray-500">Active</div></div><div className="card text-center"><div className="text-2xl font-bold text-yellow-600">{tenants.filter(t => t.status === 'Trial').length}</div><div className="text-sm text-gray-500">Trial</div></div><div className="card text-center"><div className="text-2xl font-bold text-red-600">{tenants.filter(t => t.status === 'Past Due' || t.status === 'Suspended').length}</div><div className="text-sm text-gray-500">Issues</div></div></div><div className="card overflow-hidden p-0"><div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between"><h3 className="font-bold text-gray-900">All Tenants</h3><button onClick={handleCreateTenant} className="btn-primary text-sm py-2">+ Create Tenant</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr className="text-left text-gray-500"><th className="px-6 py-3 font-medium">Tenant</th><th className="px-6 py-3 font-medium">Plan</th><th className="px-6 py-3 font-medium">Status</th><th className="px-6 py-3 font-medium">Users</th><th className="px-6 py-3 font-medium">Actions</th></tr></thead><tbody>{tenants.map((tenant) => (<tr key={tenant.id} className="border-t border-gray-100 hover:bg-gray-50"><td className="px-6 py-4"><div className="font-medium text-gray-900">{tenant.name}</div><div className="text-xs text-gray-400">{tenant.id}</div></td><td className="px-6 py-4"><span className={`px-2 py-1 rounded text-xs font-medium ${tenant.plan === 'Enterprise' ? 'bg-purple-100 text-purple-700' : tenant.plan === 'Growth' ? 'bg-blue-100 text-blue-700' : 'bg-gray-100 text-gray-700'}`}>{tenant.plan}</span></td><td className="px-6 py-4"><span className={`inline-flex px-2.5 py-1 rounded-full text-xs font-medium ${tenant.status === 'Active' ? 'bg-green-100 text-green-700' : tenant.status === 'Trial' ? 'bg-blue-100 text-blue-700' : tenant.status === 'Past Due' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'}`}>{tenant.status}</span></td><td className="px-6 py-4 text-gray-600">{tenant.users}</td><td className="px-6 py-4"><div className="flex space-x-2"><button className="text-primary-600 text-xs font-medium">View</button><button onClick={() => handleImpersonate(tenant.id)} className="text-gray-400 text-xs font-medium">Impersonate</button></div></td></tr>))}</tbody></table></div></div></div>)}
        {activeSection === 'plans' && (<div className="space-y-6"><div className="grid md:grid-cols-3 gap-6">{plans.map((plan) => (<div key={plan.name} className="card"><h3 className="text-lg font-bold text-gray-900 mb-2">{plan.name}</h3><div className="text-2xl font-bold text-primary-600 mb-4">{plan.price}</div><ul className="space-y-2 text-sm text-gray-600 mb-4"><li>• Up to {plan.users} users</li><li>• {plan.distributors} distributors</li></ul><div className="pt-4 border-t border-gray-100"><span className="text-sm text-gray-500">{plan.tenants} tenants on this plan</span></div></div>))}</div><div className="card"><h3 className="font-bold text-gray-900 mb-4">Monthly Recurring Revenue</h3><div className="text-3xl font-bold text-gray-900 mb-2">₹4,85,000</div><p className="text-sm text-green-600">+12% from last month</p></div></div>)}
        {activeSection === 'health' && (<div className="space-y-6"><div className="grid md:grid-cols-2 gap-6">{Object.entries(systemHealth).map(([service, data]) => (<div key={service} className="card"><div className="flex items-center justify-between mb-4"><h3 className="font-bold text-gray-900 uppercase text-sm">{service}</h3><span className="w-3 h-3 bg-green-500 rounded-full animate-pulse"></span></div><div className="space-y-2 text-sm">{Object.entries(data).map(([key, value]) => (<div key={key} className="flex justify-between"><span className="text-gray-500 capitalize">{key.replace(/([A-Z])/g, ' $1')}</span><span className="font-medium text-gray-900">{value}</span></div>))}</div></div>))}</div><div className="card"><h3 className="font-bold text-gray-900 mb-4">Background Jobs</h3><div className="grid grid-cols-4 gap-4"><div className="text-center"><div className="text-xl font-bold text-gray-900">0</div><div className="text-xs text-gray-500">Running</div></div><div className="text-center"><div className="text-xl font-bold text-yellow-600">3</div><div className="text-xs text-gray-500">Queued</div></div><div className="text-center"><div className="text-xl font-bold text-green-600">142</div><div className="text-xs text-gray-500">Completed</div></div><div className="text-center"><div className="text-xl font-bold text-red-600">1</div><div className="text-xs text-gray-500">Failed</div></div></div></div></div>)}
        {activeSection === 'audit' && (<div className="card overflow-hidden p-0"><div className="px-6 py-4 border-b border-gray-100"><h3 className="font-bold text-gray-900">Platform Audit Log</h3></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr className="text-left text-gray-500"><th className="px-6 py-3 font-medium">Time</th><th className="px-6 py-3 font-medium">Actor</th><th className="px-6 py-3 font-medium">Action</th><th className="px-6 py-3 font-medium">Entity</th><th className="px-6 py-3 font-medium">Tenant</th></tr></thead><tbody>{auditEvents.map((event, idx) => (<tr key={idx} className="border-t border-gray-100"><td className="px-6 py-3 text-gray-500">{event.time}</td><td className="px-6 py-3 font-medium text-gray-900">{event.actor}</td><td className="px-6 py-3"><span className={`px-2 py-1 rounded text-xs font-medium ${event.action.includes('SUSPENDED') ? 'bg-red-100 text-red-700' : event.action.includes('IMPERSONATION') ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'}`}>{event.action.replace(/_/g, ' ')}</span></td><td className="px-6 py-3 text-gray-600">{event.entity}</td><td className="px-6 py-3 text-gray-500">{event.tenant}</td></tr>))}</tbody></table></div></div>)}
      </div>
    </div>
  );
}
