'use client';

import { useState } from 'react';

export default function FieldPWAPage() {
  const [activeScreen, setActiveScreen] = useState('home');
  const [isWorking, setIsWorking] = useState(false);
  const [cart, setCart] = useState<Record<string, number>>({});
  const [language, setLanguage] = useState('en');
  const [successMessage, setSuccessMessage] = useState('');

  const outlets = [
    { id: '1', name: 'Sharma General Store', address: 'Main Market, Sector 5', priority: 'high', lastVisit: '3 days ago', potential: '₹12,000' },
    { id: '2', name: 'Patel Medical Hall', address: 'Station Road', priority: 'high', lastVisit: '5 days ago', potential: '₹8,500' },
    { id: '3', name: 'Gupta Kirana Bhandar', address: 'Gandhi Nagar', priority: 'medium', lastVisit: '2 days ago', potential: '₹6,200' },
    { id: '4', name: 'Singh Electronics', address: 'Mall Road', priority: 'medium', lastVisit: '7 days ago', potential: '₹15,000' },
    { id: '5', name: 'Mishra Provision Store', address: 'Civil Lines', priority: 'low', lastVisit: '10 days ago', potential: '₹4,800' },
    { id: '6', name: 'Royal Distributors', address: 'Industrial Area', priority: 'high', lastVisit: '1 day ago', potential: '₹45,000' },
  ];

  const products = [
    { sku: 'SKU-001', name: 'Surf Excel 1kg', price: 160, stock: '245', unit: 'CASE', gst: '18%', scheme: 'Buy 10 Get 1 Free', recommendation: 'High reorder probability' },
    { sku: 'SKU-002', name: 'Colgate Max Fresh', price: 82, stock: '520', unit: 'PKT', gst: '12%', scheme: '', recommendation: 'Peer outlets buying' },
    { sku: 'SKU-003', name: 'Parle-G 200g', price: 17, stock: '1200', unit: 'PKT', gst: '5%', scheme: '', recommendation: 'Fast moving' },
    { sku: 'SKU-004', name: 'Dettol Soap 70g', price: 38, stock: '380', unit: 'PKT', gst: '18%', scheme: '', recommendation: '' },
    { sku: 'SKU-005', name: 'Amul Butter 500g', price: 230, stock: '89', unit: 'PKT', gst: '5%', scheme: '', recommendation: 'Low stock alert' },
    { sku: 'SKU-006', name: 'Tata Tea Gold 1kg', price: 420, stock: '120', unit: 'PKT', gst: '5%', scheme: '', recommendation: '' },
  ];

  const todayStats = { planned: 10, completed: 6, productive: 4, orderValue: 24500, collections: 12000 };
  const syncQueue = [{ type: 'Order', id: 'ORD-2401', status: 'synced', time: '2 min ago' }, { type: 'Visit', id: 'VIS-105', status: 'synced', time: '5 min ago' }, { type: 'Collection', id: 'PAY-003', status: 'pending', time: '10 min ago' }];

  const handleStartDay = () => { setIsWorking(true); setSuccessMessage('Day started successfully!'); setTimeout(() => setSuccessMessage(''), 2000); };
  const handleEndDay = () => { setIsWorking(false); setSuccessMessage('Day ended. DSR generated!'); setTimeout(() => setSuccessMessage(''), 2000); };
  const handleSubmitOrder = () => { setSuccessMessage('Order submitted successfully!'); setCart({}); setTimeout(() => setSuccessMessage(''), 3000); };
  const handleForceSync = () => { setSuccessMessage('Sync completed!'); setTimeout(() => setSuccessMessage(''), 2000); };

  const renderScreen = () => {
    switch (activeScreen) {
      case 'home':
        return (
          <div className="p-4 space-y-4">
            {successMessage && (<div className="bg-green-50 border border-green-200 rounded-xl p-3"><div className="flex items-center space-x-2"><span className="text-green-600">✅</span><span className="text-sm text-green-800 font-medium">{successMessage}</span></div></div>)}
            <div className="bg-gradient-to-r from-primary-600 to-primary-800 rounded-2xl p-4 text-white"><div className="text-sm opacity-80">{language === 'en' ? 'Good Morning 👋' : 'सुप्रभात 👋'}</div><div className="text-lg font-bold">Amit Singh</div><div className="text-xs opacity-80 mt-1">Zone A • Beat 3</div></div>
            <div className="bg-white rounded-xl shadow-sm border p-4"><div className="flex items-center justify-between mb-3"><span className="font-semibold text-gray-900">{language === 'en' ? "Today's Attendance" : 'आज की उपस्थिति'}</span><span className={`text-xs px-2 py-1 rounded-full ${isWorking ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}`}>{isWorking ? (language === 'en' ? 'Working' : 'कार्यरत') : (language === 'en' ? 'Not Started' : 'शुरू नहीं')}</span></div>
              {!isWorking ? (<button onClick={handleStartDay} className="w-full bg-green-600 text-white py-3 rounded-lg font-semibold text-sm">▶ {language === 'en' ? 'Start Day' : 'दिन शुरू करें'}</button>) : (<div className="space-y-2"><div className="grid grid-cols-4 gap-2 text-center"><div><div className="text-lg font-bold text-primary-600">{todayStats.planned}</div><div className="text-xs text-gray-500">Planned</div></div><div><div className="text-lg font-bold text-green-600">{todayStats.completed}</div><div className="text-xs text-gray-500">Done</div></div><div><div className="text-lg font-bold text-saffron-600">{todayStats.productive}</div><div className="text-xs text-gray-500">Productive</div></div><div><div className="text-lg font-bold text-purple-600">₹{(todayStats.orderValue/1000).toFixed(1)}K</div><div className="text-xs text-gray-500">Orders</div></div></div><button onClick={handleEndDay} className="w-full bg-red-600 text-white py-2 rounded-lg font-semibold text-sm mt-2">⏹ {language === 'en' ? 'End Day' : 'दिन समाप्त करें'}</button></div>)}
            </div>
            <div className="bg-white rounded-xl shadow-sm border p-4"><div className="flex items-center justify-between mb-3"><span className="font-semibold text-gray-900">🎯 {language === 'en' ? 'Smart Beat' : 'स्मार्ट बीट'}</span><span className="text-xs text-primary-600 font-medium">{language === 'en' ? 'View All' : 'सभी देखें'}</span></div><div className="space-y-2">{outlets.slice(0, 3).map((outlet, idx) => (<div key={outlet.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><div className="flex items-center space-x-3"><div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${idx === 0 ? 'bg-red-100 text-red-700' : idx === 1 ? 'bg-yellow-100 text-yellow-700' : 'bg-blue-100 text-blue-700'}`}>#{idx + 1}</div><div><div className="text-sm font-medium text-gray-900">{outlet.name}</div><div className="text-xs text-gray-500">{outlet.lastVisit} • {outlet.potential}</div></div></div><button onClick={() => setActiveScreen('visit')} className="text-xs bg-primary-600 text-white px-3 py-1.5 rounded-lg">Visit</button></div>))}</div></div>
            <div className="grid grid-cols-4 gap-3">{[{ icon: '📋', label: language === 'en' ? 'Orders' : 'ऑर्डर' }, { icon: '💰', label: language === 'en' ? 'Collect' : 'संग्रह' }, { icon: '🏪', label: language === 'en' ? 'Outlets' : 'आउलेट' }, { icon: '📊', label: 'DSR' }].map((action) => (<div key={action.label} className="text-center"><div className="w-12 h-12 bg-gray-100 rounded-xl flex items-center justify-center mx-auto mb-1"><span className="text-lg">{action.icon}</span></div><span className="text-xs text-gray-600">{action.label}</span></div>))}</div>
          </div>
        );
      case 'visit':
        return (<div className="p-4 space-y-4"><div className="flex items-center space-x-2"><button onClick={() => setActiveScreen('home')} className="text-primary-600">← Back</button></div><div className="bg-white rounded-xl shadow-sm border p-4"><h3 className="font-bold text-gray-900">Sharma General Store</h3><p className="text-xs text-gray-500 mt-1">Main Market, Sector 5 • 0.3 km away</p><div className="grid grid-cols-3 gap-3 mt-3"><div className="text-center bg-gray-50 rounded-lg p-2"><div className="text-sm font-bold text-gray-900">₹1.2L</div><div className="text-xs text-gray-500">Outstanding</div></div><div className="text-center bg-gray-50 rounded-lg p-2"><div className="text-sm font-bold text-gray-900">₹8,500</div><div className="text-xs text-gray-500">Last Order</div></div><div className="text-center bg-gray-50 rounded-lg p-2"><div className="text-sm font-bold text-gray-900">3 days</div><div className="text-xs text-gray-500">Since Visit</div></div></div></div><div className="bg-green-50 border border-green-200 rounded-xl p-4"><div className="flex items-center space-x-2"><span className="text-green-600">✅</span><span className="text-sm font-medium text-green-800">Verified Check-in</span></div><p className="text-xs text-green-600 mt-1">Distance: 3.2m | Accuracy: 4.5m</p></div><div className="grid grid-cols-2 gap-3"><button onClick={() => setActiveScreen('order')} className="bg-primary-600 text-white py-3 rounded-xl font-semibold text-sm">📋 New Order</button><button className="bg-green-600 text-white py-3 rounded-xl font-semibold text-sm">💰 Collect</button><button className="bg-gray-100 text-gray-700 py-3 rounded-xl font-semibold text-sm">📷 Photo</button><button className="bg-gray-100 text-gray-700 py-3 rounded-xl font-semibold text-sm">📝 Survey</button></div></div>);
      case 'order':
        return (<div className="p-4 space-y-4"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-gray-900">📋 {language === 'en' ? 'Order Booking' : 'ऑर्डर बुकिंग'}</h2><span className="text-xs bg-primary-100 text-primary-700 px-2 py-1 rounded-full">{Object.values(cart).reduce((a, b) => a + b, 0)} items</span></div><div className="bg-gray-50 rounded-xl p-3"><div className="text-sm font-medium text-gray-900">Sharma General Store</div><div className="text-xs text-gray-500">Credit: ₹1,20,000 | Available: ₹85,000</div></div><input type="text" placeholder={language === 'en' ? 'Search products...' : 'उत्पाद खोजें...'} className="w-full px-4 py-3 bg-gray-100 rounded-xl text-sm" /><div className="space-y-2">{products.map((product) => (<div key={product.sku} className="bg-white rounded-xl shadow-sm border p-3"><div className="flex items-center justify-between"><div className="flex-1"><div className="text-sm font-medium text-gray-900">{product.name}</div><div className="text-xs text-gray-500">₹{product.price} • GST {product.gst} • Stock: {product.stock}</div>{product.scheme && <div className="text-xs text-green-600 mt-1">🎁 {product.scheme}</div>}</div><div className="flex items-center space-x-2"><button onClick={() => setCart({ ...cart, [product.sku]: Math.max(0, (cart[product.sku] || 0) - 1) })} className="w-7 h-7 bg-gray-100 rounded-full text-gray-600 font-bold">−</button><span className="text-sm font-bold w-6 text-center">{cart[product.sku] || 0}</span><button onClick={() => setCart({ ...cart, [product.sku]: (cart[product.sku] || 0) + 1 })} className="w-7 h-7 bg-primary-100 rounded-full text-primary-600 font-bold">+</button></div></div></div>))}</div><div className="bg-primary-50 border border-primary-200 rounded-xl p-4 sticky bottom-20"><div className="flex justify-between font-bold border-t border-primary-200 pt-2"><span>Total</span><span>₹{Object.entries(cart).reduce((total, [sku, qty]) => { const p = products.find(pr => pr.sku === sku); return total + (p ? p.price * qty * (1 + parseFloat(p.gst) / 100) : 0); }, 0).toLocaleString()}</span></div><button onClick={handleSubmitOrder} className="w-full bg-primary-600 text-white py-3 rounded-lg font-semibold text-sm mt-3">{language === 'en' ? 'Submit Order' : 'ऑर्डर सबमिट करें'}</button></div></div>);
      case 'sync':
        return (<div className="p-4 space-y-4"><h2 className="text-lg font-bold text-gray-900">🔄 {language === 'en' ? 'Sync Centre' : 'सिंक सेंटर'}</h2><div className="bg-green-50 border border-green-200 rounded-xl p-4"><div className="flex items-center space-x-2"><span className="w-3 h-3 bg-green-500 rounded-full animate-pulse"></span><span className="text-sm font-medium text-green-800">{language === 'en' ? 'All synced' : 'सभी सिंक हो गए'}</span></div></div><div className="grid grid-cols-3 gap-3"><div className="bg-white rounded-xl shadow-sm border p-3 text-center"><div className="text-xl font-bold text-gray-900">{syncQueue.filter(q => q.status === 'pending').length}</div><div className="text-xs text-gray-500">Pending</div></div><div className="bg-white rounded-xl shadow-sm border p-3 text-center"><div className="text-xl font-bold text-green-600">{syncQueue.filter(q => q.status === 'synced').length}</div><div className="text-xs text-gray-500">Synced</div></div><div className="bg-white rounded-xl shadow-sm border p-3 text-center"><div className="text-xl font-bold text-red-600">{syncQueue.filter(q => q.status === 'failed').length}</div><div className="text-xs text-gray-500">Failed</div></div></div><button onClick={handleForceSync} className="w-full bg-primary-600 text-white py-3 rounded-xl font-semibold text-sm">🔄 {language === 'en' ? 'Force Sync' : 'फोर्स सिंक'}</button></div>);
      case 'profile':
        return (<div className="p-4 space-y-4"><h2 className="text-lg font-bold text-gray-900">👤 {language === 'en' ? 'Profile' : 'प्रोफाइल'}</h2><div className="bg-white rounded-xl shadow-sm border p-4 text-center"><div className="w-20 h-20 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-3"><span className="text-2xl font-bold text-primary-700">AS</span></div><div className="font-bold text-gray-900">Amit Singh</div><div className="text-sm text-gray-500">Sales Representative • Zone A</div></div><div className="bg-white rounded-xl shadow-sm border p-4 space-y-3"><div className="flex items-center justify-between"><span className="text-sm text-gray-600">{language === 'en' ? 'Language' : 'भाषा'}</span><select value={language} onChange={(e) => setLanguage(e.target.value)} className="text-sm border rounded px-2 py-1"><option value="en">English</option><option value="hi">हिंदी</option></select></div></div><button className="w-full bg-red-50 text-red-600 py-3 rounded-xl font-semibold text-sm">{language === 'en' ? 'Logout' : 'लॉगआउट'}</button></div>);
      default: return null;
    }
  };

  const [activeTab, setActiveTab] = useState('home');

  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center p-4"><div className="w-full max-w-[390px] h-[844px] bg-white rounded-[3rem] shadow-2xl overflow-hidden border-[8px] border-gray-900 relative"><div className="bg-primary-700 text-white px-6 py-2 flex justify-between items-center text-xs"><span>9:41 AM</span><span className="font-semibold">BharatSales AI</span><span>🔋 78%</span></div><div className="h-[calc(100%-120px)] overflow-y-auto">{renderScreen()}</div><div className="absolute bottom-0 left-0 right-0 bg-white border-t border-gray-200 px-2 py-2"><div className="flex justify-around">{[{ id: 'home', icon: '🏠', label: language === 'en' ? 'Home' : 'होम' }, { id: 'beat', icon: '🎯', label: language === 'en' ? 'Beat' : 'बीट' }, { id: 'order', icon: '📋', label: language === 'en' ? 'Order' : 'ऑर्डर' }, { id: 'sync', icon: '🔄', label: 'Sync' }, { id: 'profile', icon: '👤', label: language === 'en' ? 'Profile' : 'प्रोफाइल' }].map((tab) => (<button key={tab.id} onClick={() => { setActiveTab(tab.id); setActiveScreen(tab.id); }} className={`flex flex-col items-center py-1 px-3 rounded-lg ${activeTab === tab.id ? 'text-primary-600' : 'text-gray-400'}`}><span className="text-lg">{tab.icon}</span><span className="text-xs mt-0.5">{tab.label}</span></button>))}</div></div></div></div>
  );
}
