'use client';

import { useState } from 'react';
import Link from 'next/link';

export default function PrivacyPage() {
  const [activeSection, setActiveSection] = useState('all');
  const sections = [{ id: 'all', label: 'All' }, { id: '1', label: 'Information We Collect' }, { id: '2', label: 'Location Data' }, { id: '3', label: 'Data Security' }, { id: '4', label: 'Your Rights' }];

  return (
    <div className="min-h-screen"><nav className="fixed top-0 w-full bg-white/95 backdrop-blur-sm z-50 border-b border-gray-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex justify-between items-center h-16"><Link href="/" className="flex items-center space-x-2"><div className="w-8 h-8 bg-gradient-to-br from-primary-600 to-saffron-500 rounded-lg flex items-center justify-center"><span className="text-white font-bold text-sm">BS</span></div><span className="text-xl font-bold text-gray-900">BharatSales <span className="text-primary-600">AI</span></span></Link><Link href="/" className="text-primary-600 font-medium">← Back to Home</Link></div></div></nav>
      <section className="pt-28 pb-16 px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><h1 className="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1><p className="text-gray-600 mb-8">Last updated: July 14, 2026</p><div className="flex flex-wrap gap-2 mb-8">{sections.map((s) => (<button key={s.id} onClick={() => setActiveSection(s.id)} className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${activeSection === s.id ? 'bg-primary-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{s.label}</button>))}</div><div className="prose prose-gray max-w-none space-y-6"><h2 className="text-xl font-bold text-gray-900 mt-8">1. Information We Collect</h2><p className="text-gray-600">We collect information you provide directly, including company details, user accounts, product catalogs, outlet information, and transaction data necessary to provide our field sales automation services.</p><h2 className="text-xl font-bold text-gray-900 mt-8">2. Location Data</h2><p className="text-gray-600">With clear disclosure and consent, we collect GPS location data during active work sessions only. Location is used solely for visit verification, route optimization, and team tracking during working hours. Tracking stops automatically after End Day.</p><h2 className="text-xl font-bold text-gray-900 mt-8">3. How We Use Information</h2><p className="text-gray-600">We use collected information to provide, maintain, and improve our services; generate reports and analytics; ensure security and prevent fraud; and comply with legal obligations.</p><h2 className="text-xl font-bold text-gray-900 mt-8">4. Data Security</h2><p className="text-gray-600">We implement bank-grade encryption, tenant isolation, access controls, and regular security audits. All data is stored in Indian data centers with encrypted backups.</p><h2 className="text-xl font-bold text-gray-900 mt-8">5. Data Retention</h2><p className="text-gray-600">Data is retained according to your organization's configured retention policies. Archived tenant data is kept in read-only mode for the configured period.</p><h2 className="text-xl font-bold text-gray-900 mt-8">6. Your Rights</h2><p className="text-gray-600">You have the right to access, correct, export, and delete your data. Contact your organization administrator or our support team for assistance.</p><h2 className="text-xl font-bold text-gray-900 mt-8">7. Contact Us</h2><p className="text-gray-600">For privacy-related inquiries, contact us at privacy@bharatsales.ai</p></div></div></section>
      <footer className="bg-gray-900 text-white py-12 px-4 sm:px-6 lg:px-8"><div className="max-w-7xl mx-auto text-center text-gray-500 text-sm">© 2026 BharatSales AI. All rights reserved.</div></footer>
    </div>
  );
}
