'use client';

import { useState } from 'react';

export default function DistributorPortalPage() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [successMessage, setSuccessMessage] = useState('');

  const kpis = [{ label: 'Inventory Value', value: '₹12.5L', icon: '📦', change: '+5%' }, { label: 'Pending Orders', value: '24', icon: '📋', change: '+3' }, { label: 'Fill Rate', value: '94%', icon: '✅', change: '+2%' }, { label: 'Outstanding', value: '₹2.4L', icon: '💰', change: '-8%' }];
  const pendingOrders = [{ id: 'ORD-2401', outlet: 'Sharma General Store', amount: '₹12,400', items: 8, status: 'Pending Confirmation', date: '14 Jul 2026' }, { id: 'ORD-2400', outlet: 'Patel Medical Hall', amount: '₹8,750', items: 5, status: 'Pending Confirmation', date: '14 Jul 2026' }, { id: 'ORD-2399', outlet: 'Gupta Kirana', amount: '₹15,200', items: 12, status: 'Allocated', date: '14 Jul 2026' }, { id: 'ORD-2398', outlet: 'Singh Electronics', amount: '₹22,100', items: 15, status: 'Ready to Dispatch', date: '14 Jul 2026' }];

  const handleRefresh = () => { setSuccessMessage('Data refreshed successfully!'); setTimeout(() => setSuccessMessage(''), 2000); };

  return (
    <div className="min-h-screen bg-gray-50">
      {successMessage && (<div className="bg-green-50 border border-green-200 rounded-xl p-4 flex items-center justify-between max-w-7xl mx-auto mt-4 px-6"><div className="flex items-center space-x-2"><span className="text-green-600">✅</span><span className="text-sm text-green-800 font-medium">{successMessage}</span></div><button onClick={() => setSuccessMessage('')} className="text-green-600 hover:text-green-800">✕</button></div>)}
      <header className="bg-white border-b border-gray-200"><div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between"><div className="flex items-center space-x-3"><div className="w-10 h-10 bg-gradient-to-br from-primary-600 to-saffron-500 rounded-xl flex items-center justify-center"><span className="text-white font-bold">RD</span></div><div><h1 className="text-lg font-bold text-gray-900">Royal Distributors</h1><p className="text-xs text-gray-500">Distributor Portal</p></div></div><div className="flex items-center space-x-4"><span className="text-sm text-gray-500">Zone A & B</span><button onClick={handleRefresh} className="btn-secondary text-sm">🔄 Refresh</button></div></div></header>
      <div className="bg-white border-b border-gray-200"><div className="max-w-7xl mx-auto px-6 flex space-x-6">{[{ id: 'dashboard', label: 'Dashboard', icon: '📊' }, { id: 'orders', label: 'Orders', icon: '📋' }, { id: 'inventory', label: 'Inventory', icon: '📦' }, { id: 'dispatch', label: 'Dispatch', icon: '🚚' }, { id: 'invoices', label: 'Invoices', icon: '🧾' }, { id: 'reports', label: 'Reports', icon: '📈' }].map((tab) => (<button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex items-center space-x-2 py-3 border-b-2 text-sm font-medium transition-colors ${activeTab === tab.id ? 'border-primary-600 text-primary-600' : 'border-transparent text-gray-500 hover:text-gray-700'}`}><span>{tab.icon}</span><span>{tab.label}</span></button>))}</div></div>
      <div className="max-w-7xl mx-auto px-6 py-6">
        {activeTab === 'dashboard' && (<div className="space-y-6"><div className="grid grid-cols-4 gap-4">{kpis.map((kpi) => (<div key={kpi.label} className="card"><div className="flex items-center justify-between mb-2"><span className="text-2xl">{kpi.icon}</span><span className="text-xs text-green-600 font-medium">{kpi.change}</span></div><div className="text-2xl font-bold text-gray-900">{kpi.value}</div><div className="text-sm text-gray-500">{kpi.label}</div></div>))}</div><div className="card overflow-hidden p-0"><div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between"><h3 className="font-bold text-gray-900">Pending Orders</h3><button className="text-sm text-primary-600 font-medium">View All</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr className="text-left text-gray-500"><th className="px-6 py-3 font-medium">Order</th><th className="px-6 py-3 font-medium">Outlet</th><th className="px-6 py-3 font-medium">Items</th><th className="px-6 py-3 font-medium">Amount</th><th className="px-6 py-3 font-medium">Status</th></tr></thead><tbody>{pendingOrders.slice(0, 4).map((order) => (<tr key={order.id} className="border-t border-gray-100"><td className="px-6 py-3 font-medium text-primary-600">{order.id}</td><td className="px-6 py-3 text-gray-900">{order.outlet}</td><td className="px-6 py-3 text-gray-600">{order.items}</td><td className="px-6 py-3 font-medium">{order.amount}</td><td className="px-6 py-3"><span className={`px-2 py-1 rounded text-xs font-medium ${order.status === 'Pending Confirmation' ? 'bg-yellow-100 text-yellow-700' : order.status === 'Allocated' ? 'bg-blue-100 text-blue-700' : 'bg-green-100 text-green-700'}`}>{order.status}</span></td></tr>))}</tbody></table></div></div></div>)}
        {activeTab !== 'dashboard' && (<div className="card text-center py-12"><div className="text-4xl mb-4">{activeTab === 'orders' ? '📋' : activeTab === 'inventory' ? '📦' : activeTab === 'dispatch' ? '🚚' : activeTab === 'invoices' ? '🧾' : '📈'}</div><h3 className="text-lg font-bold text-gray-900 mb-2">{activeTab.charAt(0).toUpperCase() + activeTab.slice(1)}</h3><p className="text-gray-500">This section is available in the full distributor portal.</p></div>)}
      </div>
    </div>
  );
}
