import { BadRequestException, NotFoundException } from '../core/http-errors';
import { Logger } from '../core/logger';
import { Model } from 'mongoose';
import { Invoice, PaymentCollection, Outlet, Order } from '@bharatsales/shared-types';
import type { HierarchyService } from '../hierarchy/hierarchy.service';
import { asId } from '../core/query-safety';

export class FinanceService {
  private readonly logger = new Logger(FinanceService.name);

  constructor(
    private invoiceModel: Model<Invoice>,
    private collectionModel: Model<PaymentCollection>,
    private outletModel: Model<Outlet>,
    private orderModel: Model<Order>,
    // Needed to scope Sales Managers to their territories' outlets.
    private hierarchyService?: HierarchyService,
  ) {}

  /**
   * Outlet ids the caller may see finance data for, or null for "all"
   * (admins, or internal callers passing no user). Same rules as
   * CollectionsService.findAll: a Distributor sees outlets whose orders are
   * routed to them; other non-admins see outlets in their territories.
   */
  private async accessibleOutletIds(organizationId: string, user?: any): Promise<string[] | null> {
    if (!user || ['Super Admin', 'Organization Admin'].includes(user.role)) return null;
    if (user.role === 'Distributor') {
      const ids = await this.orderModel.distinct('outletId', {
        organizationId,
        assignedDistributorId: user.distributorId || '__none__',
      });
      return ids.map((id: any) => String(id));
    }
    if (!user.territoryIds || user.territoryIds.length === 0 || !this.hierarchyService) return [];
    const descendantIds = await this.hierarchyService.getDescendantTerritoryIds(organizationId, user.territoryIds);
    const outlets = await this.outletModel.find({ organizationId, territoryId: { $in: descendantIds } }).select('_id').exec();
    return outlets.map((o: any) => o._id.toString());
  }

  async getInvoices(organizationId: string, user?: any): Promise<Invoice[]> {
    const query: any = { organizationId };
    const outletIds = await this.accessibleOutletIds(organizationId, user);
    if (outletIds) query.outletId = { $in: outletIds };
    return this.invoiceModel.find(query).sort({ createdAt: -1 }).exec();
  }

  async generateInvoiceFromOrder(organizationId: string, orderId: string, session?: any, deliveredItems?: { productId: string, deliveredQty: number }[]): Promise<Invoice> {
    const order = await this.orderModel.findOne({ _id: asId(orderId), organizationId }).session(session);
    if (!order) {
      throw new NotFoundException('Order not found');
    }

    const existingInvoice = await this.invoiceModel.findOne({ orderId: asId(orderId), organizationId }).session(session);
    if (existingInvoice) {
      throw new BadRequestException('Invoice already generated for this order');
    }

    let invoiceTotal = order.totals.grandTotal;

    if (deliveredItems && deliveredItems.length > 0) {
      invoiceTotal = 0;
      for (const item of order.items) {
        const delivered = deliveredItems.find(d => d.productId === item.productId);
        if (delivered) {
          const discountPerUnit = (item.discount || 0) / item.quantity;
          const adjustedSubTotal = (item.unitPrice * delivered.deliveredQty) - (discountPerUnit * delivered.deliveredQty);
          const adjustedCgst = adjustedSubTotal * (item.gstPercentage / 2) / 100;
          const adjustedSgst = adjustedCgst;
          const adjustedTotal = adjustedSubTotal + adjustedCgst + adjustedSgst;
          invoiceTotal += adjustedTotal;
        }
      }
    }

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 15); // Net 15

    const invoice = new this.invoiceModel({
      organizationId,
      invoiceNumber: `INV-${Date.now()}`,
      orderId: order._id,
      outletId: order.outletId,
      totalAmount: invoiceTotal,
      paidAmount: 0,
      status: 'Unpaid',
      dueDate: dueDate.toISOString(),
    });

    const savedInvoice = await invoice.save({ session }) as any;

    // Update Outlet's outstanding balance
    await this.outletModel.updateOne(
      { _id: order.outletId, organizationId },
      { $inc: { 'commercial.outstandingBalance': invoiceTotal } },
      { session }
    );

    return savedInvoice;
  }

  async createCreditNote(organizationId: string, outletId: string, amount: number, referenceId: string, session?: any): Promise<PaymentCollection> {
    const outlet = await this.outletModel.findOne({ _id: outletId, organizationId }).session(session);
    if (!outlet) {
      throw new NotFoundException('Outlet not found');
    }

    const creditNote = new this.collectionModel({
      organizationId,
      outletId,
      collectedByUserId: 'system', // Automatically generated by system for returns
      amount: -amount, // Negative collection acts as a credit to the outlet
      paymentMode: 'Credit Note',
      referenceNumber: `CN-${referenceId}`,
      receiptNumber: `CN-${Date.now()}`,
      status: 'Cleared',
      collectionDate: new Date().toISOString()
    });

    await creditNote.save({ session });

    // Decrease outstanding balance (because they owe us less)
    outlet.commercial.outstandingBalance = Math.max(0, (outlet.commercial.outstandingBalance || 0) - amount);
    await outlet.save({ session });

    return creditNote;
  }

  async getLedger(organizationId: string, outletId: string, user?: any): Promise<any[]> {
    const outletIds = await this.accessibleOutletIds(organizationId, user);
    if (outletIds && !outletIds.includes(String(outletId))) {
      throw new NotFoundException('Outlet not found');
    }
    const invoices = await this.invoiceModel.find({ organizationId, outletId }).exec();
    const collections = await this.collectionModel.find({ organizationId, outletId }).exec();

    let ledger = [];

    for (const inv of invoices) {
      ledger.push({
        id: inv._id.toString(),
        date: inv.createdAt,
        type: 'Invoice',
        reference: inv.invoiceNumber,
        debit: inv.totalAmount,
        credit: 0,
        status: inv.status
      });
    }

    for (const col of collections) {
      if (col.status === 'Cleared' || col.status === 'Bounced') {
        let entryType = col.amount < 0 ? 'Reversal' : (col.status === 'Bounced' ? 'Bounced' : 'Collection');
        if ((col.paymentMode as string) === 'Credit Note') {
           entryType = 'Credit Note';
        }
        ledger.push({
          id: col._id.toString(),
          date: col.collectionDate || col.createdAt,
          type: entryType,
          reference: col.receiptNumber,
          debit: col.amount < 0 && entryType !== 'Credit Note' ? Math.abs(col.amount) : 0,
          credit: (col.amount > 0 && col.status !== 'Bounced') || entryType === 'Credit Note' ? Math.abs(col.amount) : 0,
          status: col.status
        });
      }
    }

    ledger.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

    let runningBalance = 0;
    for (let entry of ledger) {
      runningBalance += entry.debit;
      runningBalance -= entry.credit;
      (entry as any).runningBalance = runningBalance;
    }

    return ledger.reverse(); // Newest first for UI
  }
}
