'use client';

import { useState } from 'react';
import { OnboardingService } from '@bharatsales/api-client';
import { useRouter } from 'next/navigation';

export default function OnboardingPage() {
  const router = useRouter();
  const [currentStep, setCurrentStep] = useState(1);
  const [successMessage, setSuccessMessage] = useState('');
  const [formData, setFormData] = useState({ companyName: '', tradeName: '', gstin: '', industry: 'FMCG', timezone: 'Asia/Kolkata', fiscalYearStart: '04-01', geofenceRadius: '5', gpsAccuracy: '10', workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], shiftStart: '09:00', shiftEnd: '18:00', orderApprovalThreshold: '50000', discountAuthority: '10' });

  const steps = [{ id: 1, name: 'Company', icon: '🏢' }, { id: 2, name: 'Fiscal & Tax', icon: '📋' }, { id: 3, name: 'Policies', icon: '⚙️' }, { id: 4, name: 'Hierarchy', icon: '🌳' }, { id: 5, name: 'Users', icon: '👥' }, { id: 6, name: 'Products', icon: '📦' }, { id: 7, name: 'Channels', icon: '🏭' }, { id: 8, name: 'Go Live', icon: '🚀' }];

  const handleGoLive = async () => { 
    try {
      await OnboardingService.completeOnboarding();
      setSuccessMessage('Organization activated successfully! Redirecting to dashboard...'); 
      setTimeout(() => router.push('/dashboard'), 3000); 
    } catch (error) {
      console.error('Failed to complete onboarding', error);
      alert('Failed to activate organization.');
    }
  };
  
  const handleNextStep = async () => {
    try {
      await OnboardingService.saveStep(currentStep, formData);
      setCurrentStep(Math.min(8, currentStep + 1));
    } catch (error) {
      console.error('Failed to save step', error);
      alert('Failed to save step progress.');
    }
  };

  const handleWorkingDayToggle = (day: string) => { setFormData({ ...formData, workingDays: formData.workingDays.includes(day) ? formData.workingDays.filter(d => d !== day) : [...formData.workingDays, day] }); };

  return (
    <div className="min-h-screen bg-gray-50 flex"><div className="w-72 bg-white border-r border-gray-200 p-6"><div className="flex items-center space-x-2 mb-8"><div className="w-8 h-8 bg-gradient-to-br from-primary-600 to-saffron-500 rounded-lg flex items-center justify-center"><span className="text-white font-bold text-sm">BS</span></div><span className="font-bold text-gray-900">Onboarding</span></div><div className="space-y-2">{steps.map((step) => (<div key={step.id} className={`flex items-center space-x-3 p-3 rounded-lg cursor-pointer transition-colors ${currentStep === step.id ? 'bg-primary-50 text-primary-700' : currentStep > step.id ? 'bg-green-50 text-green-700' : 'text-gray-500'}`} onClick={() => setCurrentStep(step.id)}><div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm ${currentStep === step.id ? 'bg-primary-600 text-white' : currentStep > step.id ? 'bg-green-500 text-white' : 'bg-gray-200 text-gray-500'}`}>{currentStep > step.id ? '✓' : step.icon}</div><span className="text-sm font-medium">{step.name}</span></div>))}</div><div className="mt-8 p-4 bg-primary-50 rounded-xl"><div className="text-xs text-primary-600 font-medium mb-1">Progress</div><div className="w-full bg-primary-200 rounded-full h-2"><div className="bg-primary-600 h-2 rounded-full" style={{width: `${(currentStep / 8) * 100}%`}}></div></div><div className="text-xs text-primary-600 mt-1">Step {currentStep} of 8</div></div></div>
      <div className="flex-1 p-8"><div className="max-w-3xl mx-auto">
        {successMessage && (<div className="bg-green-50 border border-green-200 rounded-xl p-4 flex items-center justify-between mb-6"><div className="flex items-center space-x-2"><span className="text-green-600">✅</span><span className="text-sm text-green-800 font-medium">{successMessage}</span></div><button onClick={() => setSuccessMessage('')} className="text-green-600 hover:text-green-800">✕</button></div>)}
        {currentStep === 1 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Company Profile</h2><p className="text-gray-500">Tell us about your organization</p></div><div className="card space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Legal Name *</label><input type="text" className="input-field" placeholder="Your Company Pvt Ltd" value={formData.companyName} onChange={(e) => setFormData({ ...formData, companyName: e.target.value })} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Trade Name</label><input type="text" className="input-field" placeholder="Brand name" value={formData.tradeName} onChange={(e) => setFormData({ ...formData, tradeName: e.target.value })} /></div></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">GSTIN</label><input type="text" className="input-field" placeholder="29AAECR1234F1Z5" value={formData.gstin} onChange={(e) => setFormData({ ...formData, gstin: e.target.value })} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Industry *</label><select className="input-field" value={formData.industry} onChange={(e) => setFormData({ ...formData, industry: e.target.value })}><option>FMCG</option><option>Pharmaceutical</option><option>Consumer Goods</option><option>Paint & Building Materials</option><option>Agri Inputs</option></select></div></div></div></div>)}
        {currentStep === 2 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Fiscal & Tax Setup</h2><p className="text-gray-500">Configure your fiscal year and tax defaults</p></div><div className="card space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Fiscal Year Start *</label><select className="input-field" value={formData.fiscalYearStart} onChange={(e) => setFormData({ ...formData, fiscalYearStart: e.target.value })}><option value="04-01">April (01-04)</option><option value="01-01">January (01-01)</option></select></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Default GST Rate</label><select className="input-field"><option>18%</option><option>12%</option><option>5%</option><option>28%</option></select></div></div></div></div>)}
        {currentStep === 3 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Working Policies</h2><p className="text-gray-500">Configure attendance, geofence, and order policies</p></div><div className="card space-y-4"><h3 className="font-semibold text-gray-900">Attendance</h3><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Working Days</label><div className="flex flex-wrap gap-2">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => (<button key={day} onClick={() => handleWorkingDayToggle(day)} className={`px-3 py-1.5 rounded-lg text-sm font-medium ${formData.workingDays.includes(day) ? 'bg-primary-100 text-primary-700' : 'bg-gray-100 text-gray-500'}`}>{day}</button>))}</div></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Shift Start</label><input type="time" className="input-field" value={formData.shiftStart} onChange={(e) => setFormData({ ...formData, shiftStart: e.target.value })} /></div></div><h3 className="font-semibold text-gray-900 pt-4">Geofence</h3><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Geofence Radius (m)</label><input type="number" className="input-field" value={formData.geofenceRadius} onChange={(e) => setFormData({ ...formData, geofenceRadius: e.target.value })} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">GPS Accuracy (m)</label><input type="number" className="input-field" value={formData.gpsAccuracy} onChange={(e) => setFormData({ ...formData, gpsAccuracy: e.target.value })} /></div></div><h3 className="font-semibold text-gray-900 pt-4">Orders</h3><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Order Approval Threshold (₹)</label><input type="number" className="input-field" value={formData.orderApprovalThreshold} onChange={(e) => setFormData({ ...formData, orderApprovalThreshold: e.target.value })} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Discount Authority (%)</label><input type="number" className="input-field" value={formData.discountAuthority} onChange={(e) => setFormData({ ...formData, discountAuthority: e.target.value })} /></div></div></div></div>)}
        {currentStep === 4 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Sales Hierarchy</h2><p className="text-gray-500">Define your sales organization structure</p></div><div className="card"><div className="flex items-center justify-between mb-4"><h3 className="font-semibold text-gray-900">Hierarchy Structure</h3><button className="btn-primary text-sm py-2">+ Add Zone</button></div><div className="space-y-3">{[{ name: 'South Zone', regions: 2, areas: 4 }, { name: 'North Zone', regions: 1, areas: 3 }, { name: 'West Zone', regions: 2, areas: 5 }].map((zone) => (<div key={zone.name} className="p-4 bg-gray-50 rounded-lg"><div className="flex items-center justify-between"><div className="flex items-center space-x-3"><span className="text-lg">🌳</span><div><div className="font-medium text-gray-900">{zone.name}</div><div className="text-xs text-gray-500">{zone.regions} regions • {zone.areas} areas</div></div></div><button className="text-primary-600 text-sm font-medium">Manage</button></div></div>))}</div></div></div>)}
        {currentStep === 5 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">User Setup</h2><p className="text-gray-500">Invite team members or import from file</p></div><div className="card space-y-4"><div className="flex space-x-3"><button className="btn-primary text-sm py-2">+ Invite User</button><button className="btn-secondary text-sm py-2">Import from CSV</button></div><div className="space-y-2">{[{ name: 'Rahul Kumar', email: 'rahul@company.com', role: 'Sales Manager', status: 'Active' }, { name: 'Amit Singh', email: 'amit@company.com', role: 'Sales Rep', status: 'Invited' }].map((user) => (<div key={user.email} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><div className="flex items-center space-x-3"><div className="w-8 h-8 bg-primary-100 rounded-full flex items-center justify-center text-xs font-bold text-primary-700">{user.name.split(' ').map(n => n[0]).join('')}</div><div><div className="text-sm font-medium text-gray-900">{user.name}</div><div className="text-xs text-gray-500">{user.email} • {user.role}</div></div></div><span className={`text-xs px-2 py-1 rounded-full ${user.status === 'Active' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>{user.status}</span></div>))}</div></div></div>)}
        {currentStep === 6 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Product Import</h2><p className="text-gray-500">Import your product catalog</p></div><div className="card space-y-4"><div className="border-2 border-dashed border-gray-300 rounded-xl p-8 text-center"><div className="text-4xl mb-4">📦</div><p className="text-sm text-gray-600 mb-2">Upload your product catalog</p><div className="flex justify-center space-x-3"><button className="btn-secondary text-sm py-2">Download Template</button><button className="btn-primary text-sm py-2">Upload File</button></div></div></div></div>)}
        {currentStep === 7 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Channel Setup</h2><p className="text-gray-500">Add distributors, warehouses, and outlets</p></div><div className="grid md:grid-cols-3 gap-4">{[{ icon: '🏭', title: 'Distributors', desc: 'Add distribution partners', action: 'Add Distributor' }, { icon: '🏬', title: 'Warehouses', desc: 'Set up warehouse locations', action: 'Add Warehouse' }, { icon: '🏪', title: 'Outlets', desc: 'Import retail outlets', action: 'Import Outlets' }].map((item) => (<div key={item.title} className="card text-center"><div className="text-3xl mb-2">{item.icon}</div><h3 className="font-semibold text-gray-900 mb-1">{item.title}</h3><p className="text-xs text-gray-500 mb-3">{item.desc}</p><button className="btn-primary text-xs py-2 w-full">{item.action}</button></div>))}</div></div>)}
        {currentStep === 8 && (<div className="space-y-6"><div><h2 className="text-2xl font-bold text-gray-900">Go Live</h2><p className="text-gray-500">Review and activate your organization</p></div><div className="card space-y-4"><h3 className="font-semibold text-gray-900">Validation Summary</h3><div className="space-y-3">{[{ label: 'Company Profile', status: 'Complete', ok: true }, { label: 'Fiscal & Tax Setup', status: 'Complete', ok: true }, { label: 'Policies Configured', status: 'Complete', ok: true }, { label: 'Hierarchy Created', status: '3 zones', ok: true }, { label: 'Users Invited', status: '3 users', ok: true }, { label: 'Products Imported', status: 'Pending', ok: false }].map((item) => (<div key={item.label} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-sm text-gray-700">{item.label}</span><span className={`text-xs font-medium ${item.ok ? 'text-green-600' : 'text-yellow-600'}`}>{item.ok ? '✓' : '⚠️'} {item.status}</span></div>))}</div><button onClick={handleGoLive} className="w-full btn-primary text-center py-3">🚀 Activate & Go Live</button></div></div>)}
        <div className="flex justify-between mt-8"><button onClick={() => setCurrentStep(Math.max(1, currentStep - 1))} disabled={currentStep === 1} className="btn-secondary disabled:opacity-50">← Previous</button><button onClick={handleNextStep} disabled={currentStep === 8} className="btn-primary disabled:opacity-50">Next →</button></div>
      </div></div>
    </div>
  );
}
